(() => {
  'use strict';
  const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } };
  const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
  const notify = (message, type = 'success') => { let el=document.querySelector('.site-alert'); if(!el){el=document.createElement('div');el.className='site-alert';document.body.appendChild(el)} el.textContent=message;el.dataset.type=type;el.classList.add('is-visible');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('is-visible'),4000); };
  const injectUI = () => { const s=document.createElement('style');s.textContent='.site-alert{position:fixed;right:20px;bottom:20px;z-index:30;max-width:360px;padding:14px 18px;border-radius:12px;background:#123c35;color:#fff;box-shadow:0 12px 30px #123c3540;transform:translateY(20px);opacity:0;pointer-events:none;transition:.25s;font-weight:700}.site-alert.is-visible{transform:none;opacity:1}.site-alert[data-type=error]{background:#9b4438}.is-invalid{border-color:#c65345!important;outline:3px solid #c6534522}.file-name{display:block;margin-top:8px;color:#667572;font-size:.85rem}';document.head.appendChild(s); };
  const menu = () => { const b=document.querySelector('.menu-toggle'),n=document.querySelector('nav'); if(!b||!n)return; b.setAttribute('aria-expanded','false');b.addEventListener('click',()=>{const open=n.classList.toggle('is-open');b.setAttribute('aria-expanded',open);b.setAttribute('aria-label',open?'Close menu':'Open menu')});n.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>n.classList.remove('is-open'))); };
  const animations = () => { document.querySelectorAll('.section,.feature-card,.talent-card,.form-card,.work-card,.page-hero,.dashboard-grid').forEach(el=>el.classList.add('reveal')); const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el)); };
  const filters = () => { const input=document.querySelector('.filters input'),select=document.querySelector('.filters select'),cards=[...document.querySelectorAll('.talent-card')];if(!cards.length)return;const run=()=>{let shown=0,q=(input?.value||'').toLowerCase(),c=(select?.value||'').toLowerCase();cards.forEach(card=>{const text=card.textContent.toLowerCase(),ok=(!q||text.includes(q))&&(!c||c==='all'||text.includes(c));card.hidden=!ok;if(ok)shown++});let empty=document.querySelector('.filter-empty');if(!shown){if(!empty){empty=document.createElement('p');empty.className='filter-empty';document.querySelector('.talent-grid')?.append(empty)}empty.textContent='No matching talent found.'}else empty?.remove()};input?.addEventListener('input',run);select?.addEventListener('change',run); };
  const files = () => document.querySelectorAll('input[type=file]').forEach(input=>input.addEventListener('change',()=>{let el=input.parentElement.querySelector('.file-name');if(!el){el=document.createElement('small');el.className='file-name';input.parentElement.append(el)}el.textContent=input.files.length?`${input.files.length} file${input.files.length>1?'s':''} selected`:'No file selected'}));
  const forms = () => document.querySelectorAll('form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();let valid=true;form.querySelectorAll('input,select,textarea').forEach(f=>{const bad=f.required&&!f.value.trim();f.classList.toggle('is-invalid',bad);if(bad)valid=false});const pw=form.querySelector('input[type=password]'),confirm=form.querySelector('[name*=confirm i],[id*=confirm i]');if(pw&&pw.value.length<8){notify('Password must be at least 8 characters.','error');return}if(confirm&&pw&&confirm.value!==pw.value){notify('Passwords do not match.','error');return}if(!valid){notify('Please complete the required fields.','error');return}const data=Object.fromEntries(new FormData(form).entries());const isSignup=/signup|register|create/i.test(`${form.action} ${form.className} ${form.id} ${document.title}`);if(isSignup)write('aganze-demo-user',{name:data.name||data.fullname||data.email?.split('@')[0]||'Aganze member',email:data.email||''});if(form.querySelector('input[type=file]')){const list=read('aganze-simulations',[]);list.push({title:data.title||data.name||'New simulation',created:new Date().toISOString()});write('aganze-simulations',list)}notify(form.dataset.successMessage||'Your information was submitted successfully.');form.reset()}));
  const init=()=>{injectUI();menu();animations();filters();files();forms();}; document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
