-- Run this script in Supabase SQL Editor before connecting the website.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'candidate' check (role in ('candidate','company')),
  headline text,
  bio text,
  location text,
  skills text[] default '{}',
  website text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.simulations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text,
  file_path text,
  file_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.simulations enable row level security;
alter table public.contact_messages enable row level security;

create policy "Profiles are publicly readable" on public.profiles for select using (true);
create policy "Users can create their profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can delete their profile" on public.profiles for delete using (auth.uid() = id);
create policy "Users can manage their simulations" on public.simulations for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Anyone can send a contact message" on public.contact_messages for insert with check (true);

insert into storage.buckets (id, name, public) values ('simulations', 'simulations', false) on conflict (id) do nothing;
create policy "Users manage their own simulation files" on storage.objects for all using (bucket_id = 'simulations' and auth.uid()::text = (storage.foldername(name))[1]) with check (bucket_id = 'simulations' and auth.uid()::text = (storage.foldername(name))[1]);
