-- Aganze marketplace security and trust schema.
-- Run in Supabase SQL Editor on a new project, or migrate carefully in staging first.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'candidate' check (role in ('candidate','company')),
  headline text,
  bio text,
  location text,
  skills text[] not null default '{}',
  website text,
  company_name text,
  company_website text,
  is_public boolean not null default false,
  is_verified boolean not null default false,
  verification_status text not null default 'unverified' check (verification_status in ('unverified','pending','verified','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.simulations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 3 and 160),
  description text check (description is null or char_length(description) <= 5000),
  category text,
  file_path text,
  file_name text,
  evidence_url text,
  issuer_name text,
  completed_on date,
  verification_status text not null default 'pending' check (verification_status in ('pending','approved','rejected')),
  verification_notes text,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  email text not null check (char_length(email) <= 320),
  message text not null check (char_length(message) between 10 and 5000),
  created_at timestamptz not null default now()
);

create table if not exists public.contact_requests (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.profiles(id) on delete cascade,
  candidate_id uuid not null references public.profiles(id) on delete cascade,
  subject text not null check (char_length(subject) between 3 and 160),
  message text not null check (char_length(message) between 10 and 5000),
  status text not null default 'pending' check (status in ('pending','accepted','declined','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (company_id <> candidate_id)
);

create table if not exists public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reported_profile_id uuid references public.profiles(id) on delete cascade,
  reported_simulation_id uuid references public.simulations(id) on delete cascade,
  reason text not null check (char_length(reason) between 10 and 2000),
  status text not null default 'open' check (status in ('open','reviewing','resolved','dismissed')),
  created_at timestamptz not null default now(),
  check (reported_profile_id is not null or reported_simulation_id is not null)
);

create index if not exists profiles_discovery_idx on public.profiles (role, is_public, verification_status, updated_at desc);
create index if not exists simulations_discovery_idx on public.simulations (user_id, is_public, verification_status, created_at desc);
create index if not exists requests_candidate_idx on public.contact_requests (candidate_id, status, updated_at desc);
create index if not exists requests_company_idx on public.contact_requests (company_id, status, updated_at desc);

create or replace function public.is_company() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'company' and is_verified = true);
$$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and verification_status = 'verified' and role = 'company' and company_name = 'Aganze Admin');
$$;

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
drop trigger if exists simulations_touch on public.simulations;
create trigger simulations_touch before update on public.simulations for each row execute function public.touch_updated_at();
drop trigger if exists requests_touch on public.contact_requests;
create trigger requests_touch before update on public.contact_requests for each row execute function public.touch_updated_at();

-- Users cannot promote themselves, change roles, or mark evidence/company accounts as verified.
create or replace function public.protect_trust_fields() returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is not null and not public.is_admin() then
    if tg_op = 'UPDATE' and (new.role <> old.role or new.is_verified <> old.is_verified or new.verification_status <> old.verification_status) then
      raise exception 'Trust and role fields can only be changed by an administrator';
    end if;
    new.role := case when tg_op = 'UPDATE' then old.role else coalesce(new.role, 'candidate') end;
    new.is_verified := case when tg_op = 'UPDATE' then old.is_verified else false end;
    new.verification_status := case when tg_op = 'UPDATE' then old.verification_status else 'unverified' end;
  end if;
  return new;
end; $$;
drop trigger if exists profiles_protect_trust on public.profiles;
create trigger profiles_protect_trust before insert or update on public.profiles for each row execute function public.protect_trust_fields();

alter table public.profiles enable row level security;
alter table public.simulations enable row level security;
alter table public.contact_messages enable row level security;
alter table public.contact_requests enable row level security;
alter table public.blocks enable row level security;
alter table public.reports enable row level security;

drop policy if exists "Profiles are publicly readable" on public.profiles;
drop policy if exists "Users can create their profile" on public.profiles;
drop policy if exists "Users can update their profile" on public.profiles;
drop policy if exists "Users can delete their profile" on public.profiles;
create policy profiles_select on public.profiles for select using (
  id = auth.uid() or (role = 'candidate' and is_public = true and verification_status in ('pending','verified') and public.is_company())
);
create policy profiles_insert on public.profiles for insert with check (auth.uid() = id);
create policy profiles_update on public.profiles for update using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());
create policy profiles_delete on public.profiles for delete using (id = auth.uid() or public.is_admin());

drop policy if exists "Users can manage their simulations" on public.simulations;
create policy simulations_owner on public.simulations for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy simulations_discovery on public.simulations for select using (
  public.is_company() and is_public = true and verification_status = 'approved'
  and exists (select 1 from public.profiles p where p.id = simulations.user_id and p.role = 'candidate' and p.is_public = true)
);

create policy contact_messages_insert on public.contact_messages for insert with check (true);
create policy contact_messages_admin on public.contact_messages for select using (public.is_admin());

create policy requests_insert_company on public.contact_requests for insert with check (
  company_id = auth.uid() and public.is_company()
  and exists (select 1 from public.profiles p where p.id = candidate_id and p.role = 'candidate' and p.is_public = true)
  and not exists (select 1 from public.blocks b where b.blocker_id = candidate_id and b.blocked_id = auth.uid())
);
create policy requests_participants_read on public.contact_requests for select using (company_id = auth.uid() or candidate_id = auth.uid());
create policy requests_candidate_update on public.contact_requests for update using (candidate_id = auth.uid()) with check (candidate_id = auth.uid());
create policy requests_company_update on public.contact_requests for update using (company_id = auth.uid()) with check (company_id = auth.uid());

drop policy if exists "Users manage their own simulation files" on storage.objects;
create policy simulation_files_owner on storage.objects for all using (bucket_id = 'simulations' and auth.uid()::text = (storage.foldername(name))[1]) with check (bucket_id = 'simulations' and auth.uid()::text = (storage.foldername(name))[1]);
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('simulations', 'simulations', false, 10485760, array['application/pdf','image/png','image/jpeg','text/plain','application/zip']) on conflict (id) do update set public = false, file_size_limit = 10485760;

create policy blocks_owner on public.blocks for all using (blocker_id = auth.uid()) with check (blocker_id = auth.uid());
create policy reports_insert on public.reports for insert with check (reporter_id = auth.uid());
create policy reports_owner on public.reports for select using (reporter_id = auth.uid() or public.is_admin());
create policy reports_admin_update on public.reports for update using (public.is_admin()) with check (public.is_admin());

-- Only selected fields are exposed through this view for employer discovery.
create or replace view public.public_candidate_profiles with (security_invoker = true) as
select id, full_name, headline, bio, location, skills, website, is_verified, updated_at
from public.profiles
where role = 'candidate' and is_public = true and verification_status in ('pending','verified');
